title: Settings
data:
  site_name: 'Page Blocks'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:email@test.com'
      icon: site/social-icons/email.svg
